#ifndef __CAMPAIGN_DATA_H__
#define __CAMPAIGN_DATA_H__


#pragma region LOCATIONS


int g_campaignData[][2] = {
	{138,155},
	{182,118},
	{193,159},
	{229,145},
	{292,121},
	{366,134},
	{449,133},
	{340,187},
	{268,206},
	{315,230},
	{206,276},
	{270,274},
	{285,316},
	{189,321},
	{246,428},
	{318,368},
	{408,341},
	{486,265},
	{565,202},
	{686,126},
	{819,51},
	{733,76},
	{318,473},
	{411,544},
	{473,518},
	{444,445},
	{551,565},
	{496,623},
	{396,625},
	{426,688},
	{427,661},
	{633,622},
	{625,684},
	{547,688},
	{564,796},
	{585,772},
	{471,835},
	{491,925},
	{538,959},
	{516,921},
	{1034,817},
	{1059,818},
	{1129,737},
	{1065,737},
	{992,699},
	{1035,665},
	{1092,665},
	{1155,677},
	{1145,625},
	{1167,564},
	{1224,501},
	{1208,697},
	{1178,514},
	{1150,491},
	{823,505},
	{870,537},
	{950,533},
	{910,502},
	{806,424},
	{842,461},
	{1096,392},
	{1062,374},
	{1107,369},
	{1139,357},
	{1156,406},
	{1186,409},
	{1185,447},
	{1194,478},
	{1215,470},
	{1247,449},
	{1275,424},
	{1247,421},
	{1193,366},
	{1161,344},
	{1126,312},
	{1187,307},
	{1232,333},
	{1283,386},
	{1046,313},
	{1043,284},
	{1061,274},
	{1024,263},
	{998,234},
	{966,249},
	{937,266},
	{994,292},
	{914,271},
	{910,293},
	{901,319},
	{878,315},
	{871,283},
	{901,220},
	{892,191},
	{873,212},
	{915,251},
	{970,211},
	{982,170},
	{1003,128},
	{1066,108},
	{1055,142},
	{1149,147},
	{1090,182},
	{1057,223},
	{1141,238},
	{1183,192},
	{1244,183},
	{1296,129},
	{1181,127},
	{1484,80},
	{1353,92},
	{1528,127},
	{1269,387},
	{1388,380},
	{1395,453},
	{1401,499},
	{1429,442},
	{1533,463},
	{1581,504},
	{1593,481},
	{1574,607},
	{1546,574},
	{1627,592},
	{1658,548},
	{1748,685},
	{1787,711},
	{1805,683},
	{1840,740},
	{1792,839},
	{1758,828},
	{1626,800},
	{1668,796},
	{1785,601},
	{1844,637},
	{1657,545},
	{1660,291},
	{1686,331},
	{1740,333},
	{1747,307},
	{1770,204},
	{1768,131},
	{1673,114},
	{1654,250},
	{1639,381},
	{1608,380},
	{1592,351},
	{1502,276},
	{1388,305},
	{1351,215},
	{1454,192},
	{1600,187},
	{1453,259},
	{1528,373},
	{1419,390},
	{1321,334}
};



#pragma endregion


#pragma region CONTENT



char* g_campaignContent[][2] = {
	{"CITY", "One of the biggest mainframe in the world."}, //153 + 166 = 319
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."},
	{"CITY", "One of the biggest mainframe in the world."}
};

#pragma endregion




#endif //__CAMPAIGN_DATA_H__